### PR TITLE
Resolve #13 Import OxyPlot.Blazor.js from root (absolute import)

### LINKED ISSUE #13: Import OxyPlot.Blazor.js from root (absolute import)
When using the nuget package of this project, I notice that ResizeObserver relatively imports the js file (e.g. http://localhost:1/my-path_content/OxyPlot.Blazor/OxyPlot.Blazor.js (no slash in between my-path and _content, but this is probably due to our side format).

The cause of the issue is the [relative path import](https://github.com/belucha/oxyplot.blazor/blob/760e3e2f3243b9e0b089365fc1df584d7c3db0f3/OxyPlot.Blazor/ResizeObserver/ResizeObserver.cs#L32C91-L32C91) here. 

As far as I know, most application use the same wwwroot at the root, so using absolute import (`/_content/OxyPlot.Blazor/OxyPlot.Blazor.js`) facilitates the integration of this awesome library

### PR DESCRIPTION
**Pull request by phuongdoan13**

### CODE REVIEW

**Comment by phuongdoan13** [comment]
Hi @belucha, thank you for your awesome library. Please find my proposal to resolve issue #13

**Comment by belucha** [comment]
@phuongdoan13 thank you for the merge request, which seems reasonable.
However I do not understand yet fully, why this does not work, since it follows the MS recomendations.

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-7.0&tabs=visual-studio#create-an-rcl-with-javascript-files-collocated-with-components

They explicitly have the leading `./_content/...` part in the import statement.

Do you have any hints for me?

**Comment by phuongdoan13** [comment]
Hi @belucha, thank you for your patience, thank you for your patience. After discussing with the team, we figured out that we didn't have <base href="~/" /> in our _Host.cshtml :) Nothing wrong with your code.

**Comment by phuongdoan13** [comment]
I have another question. It seems to me that this package on nuget is not strongly signed, which causes us a lot of trouble integrating it into the system. I wonder if there is any reason to not sign it.

**Comment by belucha** [comment]
I investigated some short time in strongly signing and did not have success.
I don't see other libraries like MudBlazor strongly signed either.
Besides I will close this pull request since it is unrelated anyway.

**Pull request closed without merging**
